import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MenuButton from '../components/MenuButton'
import MailForm from '../components/MailForm'
import Gallery from '../components/Gallery'
import { useState, useEffect } from 'react'
import Loader from 'react-loader-spinner'

const Home: NextPage = () => {
  const [ loading, setLoading ] = useState<Boolean>(true)
  
  useEffect(() => {
    window.addEventListener("load", () => setLoading(false))
  })

  if (loading) {
    return (
      <div style={{ width: '100vw', height: '100vh', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
      <Loader
        type="ThreeDots"
        color="gray"
        height={80}
        width={80}
        timeout={0}
      />
      </div>
    )
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <text>永眠</text>
          <MenuButton />
        </div>
        <div className={loading ? styles["video-conteiner"] : styles["video-container-animated"]}>
          <video autoPlay loop muted src="background.mp4" className={styles["background-video"]} />
        </div>
        <Gallery works={[ { imageUrl: "/work1.jpg", title: "泣いてる私も面倒臭がらずに愛してよ" }, { imageUrl: "/work2.jpg", title: "死んでるみたいに生きている" } ]}/>
        <MailForm />
      </main>

      {/*
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      */}
    </div>
  )
}

export default Home
